### ISSUE TITLE
Using along with aws-iam-authenticator

### ISSUE THREAD

**Issue by mazzy89** [99designs/aws-vault#344]
I'm trying to using `aws-vault` with `aws-iam-authenticator

This is the `users` block of the `kubeconfig` file.

```yaml
  - name: mycluster-aws-auth
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - token
          - -i
          - mycluster
        command: aws-vault exec kubernetes-admin -- aws-iam-authenticator
```

What I get when I try to run it is this error:

```
Unable to connect to the server: getting token: exec: exec: "aws-vault exec kubernetes-admin -- aws-iam-authenticator": executable file not found in $PATH
```

**Comment by jasonbrownbridge** [comment]
I had luck with something similar to below. If the `--forward-session-name` argument causes issues you can comment it out or get a newer version of aws-iam-authenticator. The role should be the same one you used when you configured the server side component of aws-iam-authenticator.
```yaml
- name: mycluster-aws-auth
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-vault
      args:
        - "exec"
        - "default"
        - "--"
        -  "aws-iam-authenticator"
        - "token"
        - "-i"
        - "mycluster"
        - "--role"
        - "arn::ROLE_TO_ASSUME"
        - "--forward-session-name"
```

**Comment by jasonbrownbridge** [comment]
If you still run into the same issue try to use the fully qualified paths which you can find by doing
```bash
which aws-vault
which aws-iam-authenticator
```
Increasing the debug verbosity for the kubectl command might also help you track down further errors e.g.
```bash
kubectl -v=8 get pods
```

**Comment by mazzy89** [comment]
@jasonbrownbridge thanks a lot. it worked like a charm

**Comment by danopia** [comment]
In case it's useful, I ended up embedding a shell script in my kubectl to allow for more flexible aws-vault usage. This script lets you enter an `aws-vault exec` shell and use kubectl commands without the overhead of calling into vault for each command. It also blocks you from accidentally being in the wrong vault.

```yaml
- name: aws-vault@mgmt-use1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - -c
      - |
        Profile="mgmt"
        EksCluster="mgmt-use1"
        AuthCmd="aws-iam-authenticator token -i $EksCluster --forward-session-name"
        if [ -z "$AWS_VAULT" ]
        then exec aws-vault exec $Profile -- $AuthCmd
        elif [ "$AWS_VAULT" = "$Profile" ]
        then exec $AuthCmd
        else
        >&2 echo "--> Currently in $AWS_VAULT account, but tried accessing cluster in $Profile"
        exit 1
        fi
      command: sh
      env: null
```

Update `Profile` and `EksCluster` to match your needs, the test of the script can remain.

As far as the OP issue - `command` is fed into the OS raw, so the OS was looking for a binary literally named like that long multiword string. The vault args are in the wrong place in the yaml.

**Comment by mtibben** [comment]
Please do add these tips to the USAGE.md doc in a PR!

**Comment by jwenz723** [comment]
I was able to accomplish using aws-vault in my kubeconfig like this (this is using aws cli rather than `aws-iam-authenticator`, but essentially the same):

```yaml
- name: arn:aws:eks:us-west-2:12345678990:cluster/my-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - -c
      - aws-vault exec my-profile -- aws eks get-token --region us-west-2 --cluster-name my-cluster
      command: sh
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Comment by pirxthepilot** [comment]
I couldn't get @jasonbrownbridge 's method to work exactly - for some reason I get a 403 (Not authorized to perform sts:AssumeRole) if I let `aws-iam-authenticator` do the assuming. But if I use a profile where the role is already assumed, and remove the `--role` flag, then it works fine:

```
- name: mycluster-aws-auth
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-vault
      args:
        - "exec"
        - "already-assumed-role-profile"
        - "--"
        -  "aws-iam-authenticator"
        - "token"
        - "-i"
        - "mycluster"
        - "--forward-session-name"
```
