### ISSUE TITLE
Usage with desktop apps (ie Lens / Infra)

### ISSUE THREAD

**Issue by dotCipher** [99designs/aws-vault#561]
When using desktop apps like Lens:
https://github.com/lensapp/lens
or Infra.app:
https://infra.app/

They seem to have connection failures on a system that uses `aws-vault`.
For example, I see errors like:
```
Command failed: aws --region us-east-1 eks get-token --cluster-name cluster 
Unable to locate credentials. You can configure credentials by running "aws configure".
```
When running the Infra.app

Is there a way to get around this using `aws-vault` without having to use `aws configure` to store `~/.aws/credentials` ?

**Comment by mtibben** [comment]
Hey @dotCipher, you could try something like 
```
aws-vault exec --ecs-server PROFILE -- open /Applications/Lens.app
```

**Comment by dotCipher** [comment]
Cool, that works! Thanks

**Comment by Gowiem** [comment]
Hey @dotCipher -- Sorry to surface a stale issue, but I'm trying to get this running too. Unfortunately, I'm not having the same success. Did you have to do anything beyond what @mtibben covered?

I'm getting the following error: 

```
Connecting ...
Authentication proxy started

Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve ECS metadata: Could not connect to the endpoint URL: "http://127.0.0.1:57130"
2020/06/17 12:33:48 http: proxy error: getting credentials: exec: exit status 255
```

**Comment by frezbo** [comment]
@Gowiem I just run aws-vault in server mode and runs Lens

`aws-vault exec -s <profile>`

**Comment by Gowiem** [comment]
@frezbo Huh thanks for weighing in. That seems to have gotten me further (or at least a different error) but it doesn't seem to fix the issue. Now I'm getting: 

```
Connecting ...
Authentication proxy started
2020/06/17 12:57:58 http: proxy error: context canceled
```

**Comment by deiga** [comment]
@frezbo Can you share how your kubeconfig and your launch command for Lens looks like? I can't seem to get server to work with my config

**Comment by frezbo** [comment]
@deiga I used to run `aws-vault` in server mode and open Lens, it would just work. I never tried with the `kubeconfig` calling out to `aws-iam-authenticator`, with `aws cli` it should work

**Comment by Gowiem** [comment]
@frezbo here is a piece of my `kubeconfig` which may help you (though I have a somewhat more complicated setup due to using a yubikey): 

```
# ... 
users: 
# ... 
- name: arn:aws:eks:us-east-1:XXXXXXXXXXXX:cluster/REDACTED
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - exec
      - some-profile-name
      - --prompt=ykman
      - --
      - aws
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - REDACTED
      command: aws-vault
      env:
      - name: YKMAN_OATH_CREDENTIAL_NAME
        value: REDACTED
```
